package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import domain.model.Ticket;

public class TicketRepository extends BaseRepository {

	String insertSql = "INSERT INTO tickets(name, date, location, price, quantity) VALUES (?,?,?,?,?)";
	String selectByIdSql = "SELECT * FROM people WHERE id=?";

	PreparedStatement insert;
	PreparedStatement selectById;

	public TicketRepository(Connection connection) {
		super(connection);
		try {
			insert = connection.prepareStatement(insertSql);
			selectById = connection.prepareStatement(selectByIdSql);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Ticket get(int ticketId) {
		try {
			selectById.setInt(1, ticketId);
			ResultSet rs = selectById.executeQuery();
			while (rs.next()) {
				Ticket result = new Ticket();
				result.setId(rs.getInt("id"));
				result.setName(rs.getString("name"));
				result.setDate(rs.getString("date"));
				result.setLocation(rs.getString("location"));
				result.setPrice(rs.getInt("price"));
				result.setQuantity(rs.getInt("quantity"));
				return result;
			}
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		return null;
	}

	public void add(Ticket ticket) {
		try {
			insert.setString(1, ticket.getName());
			insert.setString(2, ticket.getDate());
			insert.setString(3, ticket.getLocation());
			insert.setInt(4, ticket.getPrice());
			insert.setInt(5, ticket.getQuantity());
			insert.executeUpdate();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}

	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE tickets(" + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(50)," 
				+ "date varchar(50)," 
				+ "location varchar(50)," 
				+ "price int(50)," 
				+ "quantity int(50)" 
				+ ")";
	}

	@Override
	protected String tableName() {
		return "tickets";
	}

}