package dao;

import java.sql.Connection;
import java.sql.SQLException;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.User;

public class UserRepository extends RepositoryBase<User> {

	public UserRepository(Connection connection, IMapResultSetIntoEntity<User> mapper) {
		super(connection,mapper);
	}
	
	@Override
	protected String createTableSql() {
		return "" + "CREATE TABLE user("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "name varchar(20)," + "surname varchar(50)" + ")";
	}

	@Override
	protected String tableName() {
		return "user";
	}

	protected String insertSql() {
		return "INSERT INTO user(name, surname) VALUES (?,?)";
	}

	protected String updateSql() {
		return "UPDATE user SET (name, surname)=(?,?) WHERE id=?";
	}


	@Override
	protected void setUpdate(User entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		
	}

	@Override
	protected void setInsert(User entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
	}
	
}
